sudo: required

cache:
  directories:
    - $HOME/wheelhouse

matrix:
  include:
    - os: osx
      osx_image: Xcode 8.3.3
      language: generic
    - os: linux
      language: python

script: 
  - ./build_pyside_wheel.sh
